// <auto-generated />
using System;
using HR.Managment.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR.Managment.Persistence.Migrations
{
    [DbContext(typeof(HrDatabaseContext))]
    [Migration("20240127080320_ini-migration")]
    partial class inimigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HR.Managment.Domain.LeaveAllocation", b =>
                {
                    b.Property<int>("LeaveAllocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveAllocationID"));

                    b.Property<string>("CreateionUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeaveAllocationPeriod")
                        .HasColumnType("int");

                    b.Property<int>("LeaveAllocationnumberOfDay")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypesID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("LeaveAllocationID");

                    b.HasIndex("LeaveTypesID");

                    b.ToTable("LeaveAllocations");
                });

            modelBuilder.Entity("HR.Managment.Domain.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveRequestID"));

                    b.Property<string>("CreateionUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("LeaveRequestApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("LeaveRequestCancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LeaveRequestDateRequested")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LeaveRequestEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveRequestRequestComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LeaveRequestStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaveTypesID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("LeaveRequestID");

                    b.HasIndex("LeaveTypesID");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("HR.Managment.Domain.LeaveTypes", b =>
                {
                    b.Property<int>("LeaveTypesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveTypesID"));

                    b.Property<string>("CreateionUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaveTypesDefaultDays")
                        .HasColumnType("int");

                    b.Property<string>("LeaveTypesName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("LeaveTypesID");

                    b.ToTable("LeaveTypes");
                });

            modelBuilder.Entity("HR.Managment.Domain.LeaveAllocation", b =>
                {
                    b.HasOne("HR.Managment.Domain.LeaveTypes", "LeaveTypes")
                        .WithMany()
                        .HasForeignKey("LeaveTypesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveTypes");
                });

            modelBuilder.Entity("HR.Managment.Domain.LeaveRequest", b =>
                {
                    b.HasOne("HR.Managment.Domain.LeaveTypes", "LeaveTypes")
                        .WithMany()
                        .HasForeignKey("LeaveTypesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
